debian/changelog

Changelog
* release dde-session 1.1.0
Log:

chore: bump version to 1.1.0

---

CMakeLists.txt
README.md
docs/design.md
src/dde-session-ctl/CMakeLists.txt
src/dde-session/CMakeLists.txt
systemd/CMakeLists.txt
systemd/dde-session-exit-task.service.in
systemd/dde-session-manager.service.in
systemd/dde-session-shutdown.service.in

chore: install dde-session-ctl to CMAKE_INSTALL_LIBEXECDIR

---

src/dde-session/othersmanager.cpp

Log:
kwin_no_scale has removed
kwinrc rename to deepin-kwinrc

chore: sync changes in deepin-kwin

---

debian/changelog

* release dde-session 1.1.1
Log:

chore: bump version to 1.1.1

---

systemd/CMakeLists.txt

add dde-osd dde-polkit-agent dde-lock service to dde-session-daemon.target.wants
Log:

chore: dde-session-daemon.target.wants some services is lost

---

debian/changelog

* release dde-session 1.1.2
Log:

chore: bump version to 1.1.2

---

systemd/CMakeLists.txt
systemd/dde-session-initialized.target.wants/dde-desktop.service
systemd/dde-session-initialized.target.wants/dde-display.target
systemd/dde-session-initialized.target.wants/dde-dock.service
systemd/dde-session-initialized.target.wants/dde-session-daemon.target
systemd/dde-session-manager.service.in
systemd/dde-session-pre.target.wants/dde-display.service
systemd/dde-session.target
systemd/dde-session@wayland.service
systemd/dde-session@x11.service

set DE component after dde-session-pre.target

fix: no environment variable on wayland session

---

debian/changelog

chore: fix changelog

---

.gitignore
.obs/workflows.yml
archlinux/PKGBUILD

chore: add archlinux build

---

debian/changelog

release dde-session 1.1.5
Log:

chore: bump version to 1.1.5

---

systemd/dde-session@wayland.service
systemd/dde-session@x11.service

chore: remove dde-session-wayland.target in dde-session@x11.service

---

tools/dde-keyring-checker/CMakeLists.txt
tools/dde-keyring-checker/dde-keyring-checker.service
tools/dde-version-checker/CMakeLists.txt
tools/dde-version-checker/dde-version-checker.service
tools/dde-xsettings-checker/CMakeLists.txt
tools/dde-xsettings-checker/dde-xsettings-checker.service

- dde-keyring-checker
- dde-login-reminder
- dde-version-checker
- dde-xsettings-checker
dde-session-daemon.target will start some services.

refactor: move to initialized.wants

---

debian/changelog

release dde-session 1.1.6
Log:

chore: bump version to 1.1.6

---

debian/changelog

release dde-session 1.1.7
Log:

chore: bump version to 1.1.7

---

systemd/dde-session-initialized.target.wants/dde-dock.service

AM service is org.desktopspec.ApplicationManager1.service

chore: update dde-dock depency

---

debian/changelog

release dde-session 1.1.8
Log:

chore: bump version to 1.1.8

---

debian/changelog

release dde-session 1.1.9
Log:

chore: bump version to 1.1.9

---

src/dde-session/impl/sessionmanager.cpp

Log:
Issue: https://github.com/linuxdeepin/developer-center/issues/6253

fix: dde-session cannot shutdown

---

misc/CMakeLists.txt
misc/Xsession.d/00deepin-dde-env
misc/Xsession.d/01deepin-profile
misc/Xsession.d/94qt_env
misc/profile.d/deepin-xdg-dir.sh

remove env update script from startdde, and add in here
Log:

chore: env update script add

---

src/dde-session/impl/sessionmanager.cpp
src/utils/dconf.cpp

fix: startdde gsettings is gone

---

src/dde-session/environmentsmanager.cpp

This reverts commit 0fe967951508862712a0e0a8941350f3d979bde5.

Revert "fix: fix-linglong app is missing"

---

debian/control
misc/Xsession.d/00deepin-dde-env

export systemd env to prevent env being overwritten by dde-session
Log:

fix: fix-linglong app is missing

---

debian/changelog

release dde-session 1.2.0
Log:

chore: release dde-session 1.2.0

---

src/dde-session/main.cpp

chore: correct a typo in main.cpp

---

debian/changelog

release dde-session 1.2.1
Log:

chore: release dde-session 1.2.1

---

misc/Xsession.d/00deepin-dde-env

we must exclude input method related environment variable or it will cause im launch script launch error
Log:

fix: fcitx5 can not start

---

debian/changelog

release dde-session 1.2.2
Log:

chore: release dde-session 1.2.2

---

misc/Xsession.d/00deepin-dde-env

chore: fix env script error

---

misc/CMakeLists.txt
misc/wayland-sessions/dde-wayland.desktop.in

delete wayland-sessions folder
Log:

chore: remove wayland entry

---

misc/Xsession.d/00deepin-dde-env
misc/Xsession.d/94qt_env

QT_QPA_PLATFORM env add dxcb
Log:

chore: QT_QPA_PLATFORM env add dxcb

---

debian/changelog

release dde-session 1.2.3
Log:

chore: release dde-session 1.2.3

---

debian/control
systemd/dde-session-pre.target.wants/dde-display.service
systemd/dde-session@x11.service

Issue: https://github.com/linuxdeepin/developer-center/issues/5743
fix lintian error by the way

fix: deepin-kwin_x11 start before startdde

---

debian/changelog

chore: release dde-session 1.2.4

---

systemd/dde-session@x11.service

adjust StartLimitBurst to 3 and RestartSec to 500ms to make sure kwin can launch normal
Log:

fix: kwin launch failed

---

debian/changelog

release dde-session 1.2.5
Log:

chore: release dde-session 1.2.5

---

src/dde-session/impl/sessionmanager.cpp
src/dde-session/impl/sessionmanager.h
src/utils/utils.h

stop dde-dock and dde-desktop before logout
Log:

fix: dock will flash when logout

---

debian/changelog

release dde-session 1.2.6
Log:

chore: release dde-session 1.2.6

---

debian/changelog
systemd/CMakeLists.txt
systemd/dde-session-initialized.target.wants/dde-shell@DDE.service

feat: dde-shell replace dde-dock

---

misc/Xsession.d/94qt_env

Deepin do't use kwin-wayland, need rm kwayland-shell env
Log:

chore: rm kwayland-shell

---

debian/changelog

chore: release 1.2.11

---

debian/changelog

chore: release 1.2.13

---

debian/changelog
systemd/dde-session-initialized.target.wants/dde-osd.service
systemd/dde-session-initialized.target.wants/dde-shell@DDE.service

chore: release 1.2.14

---

systemd/dde-session-initialized.target.wants/dde-shell@DDE.service

as title.
task: https://pms.uniontech.com/task-view-365219.html

feat: disable notification of dde-shell in x11 on community

---

debian/changelog

chore: bump dev version to 1.99.1

---

systemd/dde-session-initialized.target.wants/dde-lock.service

Treeland下,dde-lock不需要启动
task: https://pms.uniontech.com/task-view-361827.html

feat: DDE适配Treeland

---

debian/changelog

chore: bump version to 1.99.2

---

src/dde-session/environmentsmanager.cpp

设置固定24大小，当屏幕缩放时，Qt会自动对24进行缩放
pms: BUG-291607

feat: set a fixed cursor size on Wayland

---

debian/changelog

Reverts linuxdeepin/dde-session#108

Revert "chore: bump version to 1.99.5"

---

debian/changelog

release 1.99.6
Log: bump version to 1.99.6

chore: bump version to 1.99.6

---

debian/changelog

chore: bump version 1.99.7

---

src/dde-session/environmentsmanager.cpp

fix: not reconnect to treeland

---

debian/changelog

* fix: not reconnect to treeland
* fix: the language change in Treeland is not work

chore: bump version to 1.99.8

---

debian/changelog

chore: bump version to 1.99.9

---

misc/Xsession.d/00deepin-dde-env

lshw执行高概率卡主
Log: 修复登录桌面过慢问题问题
pms: BUG-305683

fix: 修复从登录页面到桌面加载时间大约需要2分钟问题

---

debian/changelog

chore: bump version to 1.99.10
