linuxdeepin/dde-session

src/dde-session/impl/sessionmanager.cpp, src/dde-session/impl/sessionmanager.h
属性变化时,需要服务提供方主动通知DBus,之前都是没通知的
Log: 修复SessionManager属性变化无法监听的问题
Influence: 暂无
Task: https://pms.uniontech.com/task-view-230459.html
Change-Id: Iae643a54536418e8f3999b0d93271fc646fcbfb0
=> fix: 修复SessionManager属性变化无法监听的问题

src/dde-session/impl/sessionmanager.cpp
通过dde-switchtogreeter切换用户后，调用RequestLock会导致dde-session主线程阻塞 切换用户时，dde-lock已经绑定锁定信号进行了相关处理，dde-session只需要更新锁定信号即可
Log: 修复切换用户后打开关机界面异常的问题
Bug: https://github.com/linuxdeepin/developer-center/issues/3584
Influence: 登录/锁屏账户切换
=> fix: 切换用户后打开关机界面异常

src/dde-session/environmentsmanager.cpp
使用 DDE 作为当前桌面环境的名称。
注意，检查并使用 XDG_CURRENT_DESKTOP 环境变量的 DDE 组件与应用应当能正常处理 DDE 作为桌面环境名称的情况。
相关：
- https://github.com/linuxdeepin/developer-center/issues/3829
=> chore!: use DDE for current desktop name

misc/wayland-sessions/dde-wayland.desktop.in, misc/xsessions/dde-x11.desktop.in
Temporarily restore the name of the desktop environment as deepin, and adjust it to DDE when the official version is released
=> fix: wine window shadows not following

src/dde-session/environmentsmanager.cpp
when logout by wayland, and re-login to x11.
unset QT_WAYLAND_SHELL_INTEGRATION environment variable.
=> fix: dapplication cannot load icon

src/dde-session-ctl/main.cpp, src/dde-session/impl/sessionmanager.cpp, src/dde-session/main.cpp, systemd/dde-session-shutdown.target
It is necessary to ensure that the session is the last to exit, otherwise Xorg exit will cause all processes to crash.
=> fix: not in the correct exit order

tools/dde-xsettings-checker/xsettingschecker.cpp, tools/dde-xsettings-checker/xsettingschecker.h
Use fontconfig configuration to implement different fonts for different languages instead of regenerating
the fontconfig configuration after switching languages.
=> chore: remove Qt font set through xsettings

src/CMakeLists.txt, systemd/dde-session-initialized.target.wants/dde-desktop.service
dde-desktop启动依赖dde-appearance服务
Log: 修复设置自定义壁纸后桌面壁纸黑屏的问题
Influence: 桌面壁纸正确显示
Resolve: https://github.com/linuxdeepin/developer-center/issues/4778
=> fix: dde-desktop启动应依赖dde-appearance服务

src/dde-session/impl/sessionmanager.cpp, src/dde-session/impl/sessionmanager.h, src/utils/utils.h
pipewire should be stop in logout
Log: 修复注销后重新登录无法识别到声音设备的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/5193
=> fix: stop pipewire in logout

systemd/dde-session-initialized.target.wants/dde-lock.service
Lock's network is invalid in dde-lock, it need dde-session-daemon's
network dbus service.
Issue: https://github.com/linuxdeepin/developer-center/issues/4916
=> fix: Disorder between dde-lock and dde-session-daemon

systemd/dde-session-initialized.target.wants/dde-dock.service
dock bluetooth module depend dde-session-daemon bluetooth service, so it must start after dde-session-daemon
Log:
=> fix: dock bluetooth module missing

src/dde-session/environmentsmanager.cpp
As the session leader, dde-session needs to process its own environment variables and update them to systemd, so that programs started through systemd can obtain the correct environment variables.
=> fix: not set all environment to systemd and dbus

src/dde-session/impl/iowait/iowaitwatcher.cpp
Use Qt::SkipEmptyParts instead.
Fixes the following warning:
```
[33/68] Building CXX object
src/dde-session/CMakeFiles/dde-session.dir/impl/iowait/iowaitwatcher.cpp.o
/home/felix/projects/deepin/dde-session/src/dde-session/impl/iowait/iowaitwatcher.cpp:
In member function ‘void IOWaitWatcher::onTimeOut()’:
/home/felix/projects/deepin/dde-session/src/dde-session/impl/iowait/iowaitwatcher.cpp:77:41:
warning: ‘QStringList QString::split(const QString&, SplitBehavior,
Qt::CaseSensitivity) const’ is deprecated: Use split(const QString &sep,
Qt::SplitBehavior ...) variant instead [-Wdeprecated-declarations]
77 |     const QStringList &list = line.split(" ",
QString::SkipEmptyParts);
|
~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> fix: qt warning about obsolete usage of QString::SkipEmptyParts

misc/CMakeLists.txt
They should not be installed to system.
=> fix: don't install .in templates

src/dde-session/environmentsmanager.cpp
systemd env(XDG_DATA_DIRS) is replaced by dde-session env so dde-session only set partially needed
Log:
=> fix: fix-linglong app is missing

debian/control
bump dde-session depends startdde version to 6.0.11
Log:
=> chore: update startdde version to 6.0.11

src/dde-session/impl/sessionmanager.cpp
dbus send is error, lead to Locked PropertiesChanged not send
Log:
=> fix: Locked PropertiesChanged signal emit error

src/dde-session/impl/sessionmanager.cpp
调用 org.deepin.dde.Audio1 接口设置 1s 超时
Issues: linuxdeepin/developer-center#7980
=> fix: logging out takes a long time

debian/changelog
* fix: logging out takes a long time
=> chore: bump version to 1.2.8

systemd/CMakeLists.txt, systemd/dde-session-initialized.target.wants/dde-shell@TreeLand.service, systemd/dde-session-pre.target.wants/dde-display.service
disable startdde and dde-shell full plugins mode on TreeLand
=> chore: limit some dde service run to x11

systemd/dde-session-pre.target.wants/dde-display.service
switch to check DISPLAY environment.
Log:
=> chore: startdde can work under xwayland

systemd/dde-session-pre.target.wants/dde-session@x11.service
当用户目录下存在快捷键配置，不进行覆盖
Issue: https://github.com/linuxdeepin/developer-center/issues/9855
=> chore: 解决修改快捷键配置重启后恢复的问题

systemd/dde-session-initialized.target.wants/dde-lock.service
Treeland下,dde-lock不需要启动
Log: DDE适配Treeland
pms: TASK-361827
=> feat: DDE适配Treeland

src/dde-session/environmentsmanager.cpp
Log: Try to fix https://github.com/linuxdeepin/developer-center/issues/9493
=> fix: dtk6 theme is not dxcb style on openSUSE and Gentoo

misc/CMakeLists.txt, misc/Xsession.d/94qt_env
由于此配置仅在 debian 下生效，现相关逻辑已移至 environmentsmanager，故不再需要此配置。
另见： https://github.com/linuxdeepin/dde-session/pull/86
=> chore: remove 94qt_env

debian/changelog
=> chore: bump version to 1.99.4

src/dde-session/environmentsmanager.cpp, systemd/dde-session-pre.target.wants/dde-display.service
add xcb fallback
add startdde after treeland-xwayland.service
Log:
=> chore: add xcb to QT_QPA_PLATFORM fallback

src/dde-session/environmentsmanager.cpp
Change the colon to a semicolon
Log: as title
=> fix: the environment variable is set incorrectly

systemd/CMakeLists.txt
Forgot to install the actual service file
log: as title
=> fix: dde-desktop unable to start

src/dde-session/environmentsmanager.cpp
treeland 下不走 Xsession。手动读取 ~/.config/locale.conf
Log: 修复 treeland 下修改语言不生效
PMS: bug-294913
=> fix: the language change in Treeland is not work

CMakeLists.txt, dbus/types/sessionpathlist.h, debian/control, src/CMakeLists.txt, src/dde-session-ctl/CMakeLists.txt, src/dde-session/CMakeLists.txt, src/dde-session/environmentsmanager.cpp, src/dde-session/impl/sessionmanager.cpp, src/dde-session/impl/sessionmanager.h, src/dde-session/main.cpp, src/utils/utils.h, tools/dde-login-reminder/CMakeLists.txt, tools/dde-login-reminder/main.cpp, tools/dde-version-checker/CMakeLists.txt, tools/dde-xsettings-checker/CMakeLists.txt, tools/dde-xsettings-checker/xsettingschecker.cpp
=> chore: adapt to Qt6

debian/changelog, misc/Xsession.d/00deepin-dde-env
Incorrect return value causes rendering engine error
pms: TASK-368711
=> fix: return value spelling error
